@startuml

title "Состояния процесса в системе"

hide empty description

state "Запрос на вход в КС" as S1
state "Вход в КС" as S2
state "Выход из КС" as S3

[*] -> S1
S1 --> S2 : получен маркер
S2 -> S3
S3 -> S1 : передача маркера\nследующему процессу

@enduml
